// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCompanyAttribute("RazorEngine")]
[assembly: AssemblyProductAttribute("RazorEngine")]
[assembly: AssemblyCopyrightAttribute("RazorEngine Copyright © RazorEngine Project 2011-2017")]
[assembly: AssemblyVersionAttribute("3.10.0")]
[assembly: AssemblyFileVersionAttribute("3.10.0")]
[assembly: AssemblyInformationalVersionAttribute("3.10.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "3.10.0";
        internal const string InformationalVersion = "3.10.0";
    }
}
