// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCompanyAttribute("RazorEngine")]
[assembly: AssemblyProductAttribute("RazorEngine")]
[assembly: AssemblyCopyrightAttribute("RazorEngine Copyright © RazorEngine Project 2011-2015")]
[assembly: AssemblyVersionAttribute("4.1.6")]
[assembly: AssemblyFileVersionAttribute("4.1.6")]
[assembly: AssemblyInformationalVersionAttribute("4.1.6-beta1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "4.1.6";
    }
}
