// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCompanyAttribute("RazorEngine.Roslyn")]
[assembly: AssemblyProductAttribute("RazorEngine.Roslyn")]
[assembly: AssemblyCopyrightAttribute("RazorEngine Copyright © RazorEngine Project 2011-2015")]
[assembly: AssemblyVersionAttribute("3.5.2")]
[assembly: AssemblyFileVersionAttribute("3.5.2")]
[assembly: AssemblyInformationalVersionAttribute("3.5.2-beta2")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "3.5.2";
    }
}
