// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCompanyAttribute("RazorEngine.Roslyn")]
[assembly: AssemblyProductAttribute("RazorEngine.Roslyn")]
[assembly: AssemblyCopyrightAttribute("RazorEngine Copyright © RazorEngine Project 2011-2015")]
[assembly: AssemblyVersionAttribute("4.1.0")]
[assembly: AssemblyFileVersionAttribute("4.1.0")]
[assembly: AssemblyInformationalVersionAttribute("4.1.0-rc1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "4.1.0";
    }
}
