// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCompanyAttribute("RazorEngine")]
[assembly: AssemblyProductAttribute("RazorEngine")]
[assembly: AssemblyCopyrightAttribute("RazorEngine Copyright © RazorEngine Project 2011-2016")]
[assembly: AssemblyVersionAttribute("3.9.0")]
[assembly: AssemblyFileVersionAttribute("3.9.0")]
[assembly: AssemblyInformationalVersionAttribute("3.9.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "3.9.0";
    }
}
