// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCompanyAttribute("RazorEngine.Roslyn")]
[assembly: AssemblyProductAttribute("RazorEngine.Roslyn")]
[assembly: AssemblyCopyrightAttribute("RazorEngine Copyright © RazorEngine Project 2011-2017")]
[assembly: AssemblyVersionAttribute("3.6.1")]
[assembly: AssemblyFileVersionAttribute("3.6.1")]
[assembly: AssemblyInformationalVersionAttribute("3.6.1-rc1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "3.6.1";
        internal const string InformationalVersion = "3.6.1-rc1";
    }
}
